### ISSUE TITLE
dmc.Group does not accept a "direction" parameter

### ISSUE THREAD

**Issue by masta79** [AnnMarieW/dash-multi-page-app-demos#12]
multi_page_nested_folders/app.py uses a direction keyword argument when calling dmc.Group. For me this results in the below error. Removing the argument defaults to all links in a group being in one row. Python 3.11, dmc 0.12.1

Traceback (most recent call last):
  File "<PATH>/dash-multi-page-app-demos/multi_page_nested_folders/app.py", line 38, in <module>
    dmc.Group(
  File "<PATH>/dash-multi-page-app-demos/.venv/lib/python3.11/site-packages/dash/development/base_component.py", line 420, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<PATH>/dash-multi-page-app-demos/.venv/lib/python3.11/site-packages/dash_mantine_components/Group.py", line 65, in __init__
    super(Group, self).__init__(children=children, **args)
  File "<PATH>/dash-multi-page-app-demos/.venv/lib/python3.11/site-packages/dash/development/base_component.py", line 138, in __init__
    raise TypeError(
TypeError: The `dash_mantine_components.Group` component (version 0.12.1) received an unexpected keyword argument: `direction`
Allowed arguments: align, bg, bgp, bgr, bgsz, bottom, c, children, className, classNames, display, ff, fs, fw, fz, grow, h, id, inset, left, lh, lts, m, mah, maw, mb, mih, miw, ml, mr, mt, mx, my, noWrap, opacity, p, pb, pl, pos, position, pr, pt, px, py, right, spacing, style, styles, sx, ta, td, top, tt, unstyled, w

**Comment by AnnMarieW** [comment]
Thanks for reporting - this example is using an older version of dash-mantine-components.  If you happen to know what needs to change, please feel free to post the solution here,  or do a pull request :slightly_smiling_face:

**Comment by masta79** [comment]
PR #13  should solve this.
